---
- hosts: test
  tasks:
  - name: Ping remote hosts
    ping:
  - name: Create /tmp/sonatel.txt file on test remote nodes
    file:
      path: /tmp/sonatel.txt
      state:  touch
  - name: Listing /tmp folder on remote nodes
    command: ls  /tmp/
    register: output
  - name: Print the output of the listing task 
    debug: var=output.stdout_lines  